//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC.Prueba.ServiceSap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OCRD", Namespace="http://schemas.datacontract.org/2004/07/SSC.Entity")]
    [System.SerializableAttribute()]
    public partial class OCRD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoExternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JrnlMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicTradNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SSC.Prueba.ServiceSap.CRD1[] LstCRD1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SSC.Prueba.ServiceSap.CampoUsuario[] LstCampoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailCountrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailCountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string U_GS_EsExtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoM {
            get {
                return this.ApellidoMField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMField, value) != true)) {
                    this.ApellidoMField = value;
                    this.RaisePropertyChanged("ApellidoM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoP {
            get {
                return this.ApellidoPField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPField, value) != true)) {
                    this.ApellidoPField = value;
                    this.RaisePropertyChanged("ApellidoP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoExterno {
            get {
                return this.CodigoExternoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoExternoField, value) != true)) {
                    this.CodigoExternoField = value;
                    this.RaisePropertyChanged("CodigoExterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_Mail {
            get {
                return this.E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MailField, value) != true)) {
                    this.E_MailField = value;
                    this.RaisePropertyChanged("E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JrnlMemo {
            get {
                return this.JrnlMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.JrnlMemoField, value) != true)) {
                    this.JrnlMemoField = value;
                    this.RaisePropertyChanged("JrnlMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicTradNum {
            get {
                return this.LicTradNumField;
            }
            set {
                if ((object.ReferenceEquals(this.LicTradNumField, value) != true)) {
                    this.LicTradNumField = value;
                    this.RaisePropertyChanged("LicTradNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SSC.Prueba.ServiceSap.CRD1[] LstCRD1 {
            get {
                return this.LstCRD1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LstCRD1Field, value) != true)) {
                    this.LstCRD1Field = value;
                    this.RaisePropertyChanged("LstCRD1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SSC.Prueba.ServiceSap.CampoUsuario[] LstCampoUsuario {
            get {
                return this.LstCampoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.LstCampoUsuarioField, value) != true)) {
                    this.LstCampoUsuarioField = value;
                    this.RaisePropertyChanged("LstCampoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCity {
            get {
                return this.MailCityField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCityField, value) != true)) {
                    this.MailCityField = value;
                    this.RaisePropertyChanged("MailCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCountr {
            get {
                return this.MailCountrField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCountrField, value) != true)) {
                    this.MailCountrField = value;
                    this.RaisePropertyChanged("MailCountr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCounty {
            get {
                return this.MailCountyField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCountyField, value) != true)) {
                    this.MailCountyField = value;
                    this.RaisePropertyChanged("MailCounty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre1 {
            get {
                return this.Nombre1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre1Field, value) != true)) {
                    this.Nombre1Field = value;
                    this.RaisePropertyChanged("Nombre1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre2 {
            get {
                return this.Nombre2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre2Field, value) != true)) {
                    this.Nombre2Field = value;
                    this.RaisePropertyChanged("Nombre2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipDoc {
            get {
                return this.TipDocField;
            }
            set {
                if ((this.TipDocField.Equals(value) != true)) {
                    this.TipDocField = value;
                    this.RaisePropertyChanged("TipDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPersona {
            get {
                return this.TipoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPersonaField, value) != true)) {
                    this.TipoPersonaField = value;
                    this.RaisePropertyChanged("TipoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string U_GS_EsExt {
            get {
                return this.U_GS_EsExtField;
            }
            set {
                if ((object.ReferenceEquals(this.U_GS_EsExtField, value) != true)) {
                    this.U_GS_EsExtField = value;
                    this.RaisePropertyChanged("U_GS_EsExt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRD1", Namespace="http://schemas.datacontract.org/2004/07/SSC.Entity")]
    [System.SerializableAttribute()]
    public partial class CRD1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingFloorRoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SSC.Prueba.ServiceSap.CampoUsuario[] LstCampoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingFloorRoom {
            get {
                return this.BuildingFloorRoomField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingFloorRoomField, value) != true)) {
                    this.BuildingFloorRoomField = value;
                    this.RaisePropertyChanged("BuildingFloorRoom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SSC.Prueba.ServiceSap.CampoUsuario[] LstCampoUsuario {
            get {
                return this.LstCampoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.LstCampoUsuarioField, value) != true)) {
                    this.LstCampoUsuarioField = value;
                    this.RaisePropertyChanged("LstCampoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNo {
            get {
                return this.StreetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNoField, value) != true)) {
                    this.StreetNoField = value;
                    this.RaisePropertyChanged("StreetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampoUsuario", Namespace="http://schemas.datacontract.org/2004/07/SSC.Entity")]
    [System.SerializableAttribute()]
    public partial class CampoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SSC.Prueba.ServiceSap.CampoUsuario.m_tipos tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SSC.Prueba.ServiceSap.CampoUsuario.m_tipos tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CampoUsuario.m_tipos", Namespace="http://schemas.datacontract.org/2004/07/SSC.Entity")]
        public enum m_tipos : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            alfanumerico = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            numerico = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            fecha = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            unidades = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            general = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OITM", Namespace="http://schemas.datacontract.org/2004/07/SSC.Entity")]
    [System.SerializableAttribute()]
    public partial class OITM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UDF1DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubClassCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FcCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RetailPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SSC.Prueba.ServiceSap.CampoUsuario[] LstCampoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleName {
            get {
                return this.StyleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleNameField, value) != true)) {
                    this.StyleNameField = value;
                    this.RaisePropertyChanged("StyleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Desc1 {
            get {
                return this.Desc1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Desc1Field, value) != true)) {
                    this.Desc1Field = value;
                    this.RaisePropertyChanged("Desc1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Desc2 {
            get {
                return this.Desc2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Desc2Field, value) != true)) {
                    this.Desc2Field = value;
                    this.RaisePropertyChanged("Desc2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Desc3 {
            get {
                return this.Desc3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Desc3Field, value) != true)) {
                    this.Desc3Field = value;
                    this.RaisePropertyChanged("Desc3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int BrandCode {
            get {
                return this.BrandCodeField;
            }
            set {
                if ((this.BrandCodeField.Equals(value) != true)) {
                    this.BrandCodeField = value;
                    this.RaisePropertyChanged("BrandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string UDF1Description {
            get {
                return this.UDF1DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.UDF1DescriptionField, value) != true)) {
                    this.UDF1DescriptionField = value;
                    this.RaisePropertyChanged("UDF1Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int DeptCode {
            get {
                return this.DeptCodeField;
            }
            set {
                if ((this.DeptCodeField.Equals(value) != true)) {
                    this.DeptCodeField = value;
                    this.RaisePropertyChanged("DeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ClassCode {
            get {
                return this.ClassCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassCodeField, value) != true)) {
                    this.ClassCodeField = value;
                    this.RaisePropertyChanged("ClassCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string SubClassCode {
            get {
                return this.SubClassCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubClassCodeField, value) != true)) {
                    this.SubClassCodeField = value;
                    this.RaisePropertyChanged("SubClassCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string SubClassName {
            get {
                return this.SubClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubClassNameField, value) != true)) {
                    this.SubClassNameField = value;
                    this.RaisePropertyChanged("SubClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public decimal FcCost {
            get {
                return this.FcCostField;
            }
            set {
                if ((this.FcCostField.Equals(value) != true)) {
                    this.FcCostField = value;
                    this.RaisePropertyChanged("FcCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public decimal RetailPrice {
            get {
                return this.RetailPriceField;
            }
            set {
                if ((this.RetailPriceField.Equals(value) != true)) {
                    this.RetailPriceField = value;
                    this.RaisePropertyChanged("RetailPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string UPC {
            get {
                return this.UPCField;
            }
            set {
                if ((object.ReferenceEquals(this.UPCField, value) != true)) {
                    this.UPCField = value;
                    this.RaisePropertyChanged("UPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string ALU {
            get {
                return this.ALUField;
            }
            set {
                if ((object.ReferenceEquals(this.ALUField, value) != true)) {
                    this.ALUField = value;
                    this.RaisePropertyChanged("ALU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string TypeCode {
            get {
                return this.TypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeCodeField, value) != true)) {
                    this.TypeCodeField = value;
                    this.RaisePropertyChanged("TypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public SSC.Prueba.ServiceSap.CampoUsuario[] LstCampoUsuario {
            get {
                return this.LstCampoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.LstCampoUsuarioField, value) != true)) {
                    this.LstCampoUsuarioField = value;
                    this.RaisePropertyChanged("LstCampoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ORTT", Namespace="http://schemas.datacontract.org/2004/07/SSC.Entity")]
    [System.SerializableAttribute()]
    public partial class ORTT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SSC.Prueba.ServiceSap.CampoUsuario[] LstCampoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SSC.Prueba.ServiceSap.CampoUsuario[] LstCampoUsuario {
            get {
                return this.LstCampoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.LstCampoUsuarioField, value) != true)) {
                    this.LstCampoUsuarioField = value;
                    this.RaisePropertyChanged("LstCampoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateDate {
            get {
                return this.RateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RateDateField, value) != true)) {
                    this.RateDateField = value;
                    this.RaisePropertyChanged("RateDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSap.IOCRD")]
    public interface IOCRD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOCRD/FP_BUSCAR_OCRD", ReplyAction="http://tempuri.org/IOCRD/FP_BUSCAR_OCRDResponse")]
        SSC.Prueba.ServiceSap.OCRD FP_BUSCAR_OCRD(SSC.Prueba.ServiceSap.OCRD ObjOCRD, string Compania, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOCRD/FP_Listar_OCRD", ReplyAction="http://tempuri.org/IOCRD/FP_Listar_OCRDResponse")]
        SSC.Prueba.ServiceSap.OCRD[] FP_Listar_OCRD(SSC.Prueba.ServiceSap.OCRD ObjOCRD, string Compania, string Key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOCRDChannel : SSC.Prueba.ServiceSap.IOCRD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OCRDClient : System.ServiceModel.ClientBase<SSC.Prueba.ServiceSap.IOCRD>, SSC.Prueba.ServiceSap.IOCRD {
        
        public OCRDClient() {
        }
        
        public OCRDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OCRDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OCRDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OCRDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SSC.Prueba.ServiceSap.OCRD FP_BUSCAR_OCRD(SSC.Prueba.ServiceSap.OCRD ObjOCRD, string Compania, string Key) {
            return base.Channel.FP_BUSCAR_OCRD(ObjOCRD, Compania, Key);
        }
        
        public SSC.Prueba.ServiceSap.OCRD[] FP_Listar_OCRD(SSC.Prueba.ServiceSap.OCRD ObjOCRD, string Compania, string Key) {
            return base.Channel.FP_Listar_OCRD(ObjOCRD, Compania, Key);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSap.IOITM")]
    public interface IOITM {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOITM/FP_LISTAR_OITM", ReplyAction="http://tempuri.org/IOITM/FP_LISTAR_OITMResponse")]
        SSC.Prueba.ServiceSap.OITM[] FP_LISTAR_OITM(string FechaIni, string FechaFin, string Compania, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOITM/FP_LISTAR_OITM_TOT", ReplyAction="http://tempuri.org/IOITM/FP_LISTAR_OITM_TOTResponse")]
        SSC.Prueba.ServiceSap.OITM[] FP_LISTAR_OITM_TOT(string Compania, string Key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOITMChannel : SSC.Prueba.ServiceSap.IOITM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OITMClient : System.ServiceModel.ClientBase<SSC.Prueba.ServiceSap.IOITM>, SSC.Prueba.ServiceSap.IOITM {
        
        public OITMClient() {
        }
        
        public OITMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OITMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OITMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OITMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SSC.Prueba.ServiceSap.OITM[] FP_LISTAR_OITM(string FechaIni, string FechaFin, string Compania, string Key) {
            return base.Channel.FP_LISTAR_OITM(FechaIni, FechaFin, Compania, Key);
        }
        
        public SSC.Prueba.ServiceSap.OITM[] FP_LISTAR_OITM_TOT(string Compania, string Key) {
            return base.Channel.FP_LISTAR_OITM_TOT(Compania, Key);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSap.IORTT")]
    public interface IORTT {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IORTT/FP_LISTAR_ORTT", ReplyAction="http://tempuri.org/IORTT/FP_LISTAR_ORTTResponse")]
        SSC.Prueba.ServiceSap.ORTT[] FP_LISTAR_ORTT(string date, string Compania, string Key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IORTTChannel : SSC.Prueba.ServiceSap.IORTT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ORTTClient : System.ServiceModel.ClientBase<SSC.Prueba.ServiceSap.IORTT>, SSC.Prueba.ServiceSap.IORTT {
        
        public ORTTClient() {
        }
        
        public ORTTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ORTTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ORTTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ORTTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SSC.Prueba.ServiceSap.ORTT[] FP_LISTAR_ORTT(string date, string Compania, string Key) {
            return base.Channel.FP_LISTAR_ORTT(date, Compania, Key);
        }
    }
}
